import { ArbolB } from '../estructuras/arboles/ArbolB.js'

const arbol = new ArbolB(2)
arbol.insertar(1)
console.log(arbol.imprimir())
arbol.insertar(2)
console.log(arbol.imprimir())
arbol.insertar(3)
console.log(arbol.imprimir())
arbol.insertar(4)
console.log(arbol.imprimir())
arbol.insertar(5)
console.log(arbol.imprimir())

arbol.eliminar(3)
console.log(arbol.imprimir())
arbol.eliminar(4)
console.log(arbol.imprimir())
//console.log(arbol.getRaiz())
console.log(arbol.getRaiz().hijos[0])
console.log(arbol.getRaiz().hijos[1])
arbol.eliminar(5)
console.log(arbol.getRaiz().hijos[0])
console.log(arbol.getRaiz().hijos[1])

console.log(arbol.imprimir())
